### ISSUE TITLE
scanning for movies in Radarr but nothing happens?

### ISSUE THREAD

**Issue by thesatman** [andyts93/plex-coming-soon#1]
Hi,

I created the docker-compose.override.yml in Docker:

version: "3.4"  # this must match the version in docker-compose.yml
services:
    plex-coming-soon:
        container_name: plexcomingsoon
        environment:
            - 'RADARR_URL=http://192.168.11.225:7878'
            - 'TMDB_API=my-tmdb-api'
            - 'RADARR_API=my-radarr-api'
            - 'LANG=en'
            - 'COUNTRY=gb'
            - INTERVAL=10
        volumes:
            - '/shared/Plex_NAS-data2/Media Server content 3/plex-coming-soon/:/trailers'
        image: andyts93/plex-coming-soon
Run composer and all looks well. In Portainer I see that the container is started. This is my log :

[2020-05-05 21:25:31,711] INFO (7) main:6 Starting script, scheduled every 10 minutes
[2020-05-05 21:25:31,713] INFO (7) plexcomingsoon:131 Starting search
[2020-05-05 21:35:38,567] INFO (7) plexcomingsoon:131 Starting search

Radarr is not registering anything. No files are being downloaded to the trailer folder. What am I missing here? Many thanks in advance.

**Comment by andyts93** [comment]
Hi @thesatman, this project was an experiment with python so it might not work well. Besides this thanks for your interest! 
I will try to help you, do you have any movie in radarr that has been released but not downloaded yet?

**Comment by thesatman** [comment]
Hello! So nice to hear from you. Wouldn't it be easier if we could take this conversation on chat? I'm on the discord dockstarter or FB messenger. What would you prefer?   
  

  

  

  
  
  
  
  
>

**Comment by andyts93** [comment]
> Hello! So nice to hear from you. Wouldn't it be easier if we could take this conversation on chat? I'm on the discord dockstarter or FB messenger. What would you prefer?
> […](#)
> On 14. mai 2020 at 21:05, Andrea Castellini ***@***.***> wrote: Hi @thesatman, this project was an experiment with python so it might not work well. Besides this thanks for your interest! I will try to help you, do you have any movie in radarr that has been released but not downloaded yet? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Feel free to contact me on discord

**Comment by thesatman** [comment]
![image](https://user-images.githubusercontent.com/8248755/81976128-59f04c00-9628-11ea-8e2e-e7f874641eef.png)

**Comment by andyts93** [comment]
#4932
